# Uncomment the next line to define a global platform for your project
# platform :ios, ’11.0’

target 'SwiftPSShiWuKu' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftPSShiWuKu

  target 'SwiftPSShiWuKuTests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'Alamofire'
pod 'Kingfisher'
pod “SwiftyJSON”
pod 'SnapKit'
pod 'ObjectMapper'
pod ‘RealmSwift’
pod 'SafeAreaExtension'
pod 'CLImagePickerTool', :git => 'https://github.com/Darren-chenchen/CLImagePickerTool.git'
pod 'RxSwift', '~> 3.6.1'           # 响应式编程框架 https://github.com/ReactiveX/RxSwift
pod 'RxCocoa', '~> 3.6.1'           # 响应式编程框架 https://github.com/ReactiveX/RxSwift
pod ‘BMPlayer’
pod 'Cache', '~> 4.0.4'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ’11.0’
use_frameworks!

pod "PagingMenuController"

post_install do |installer|
 installer.pods_project.targets.each do |target|
   target.build_configurations.each do |config|
     config.build_settings['SWIFT_VERSION'] = '3.0'
   end
 end
end

  target 'SwiftPSShiWuKuUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
